package main

import (
	"code/funcDome"
)

//倒入路径的包

func main() {
	//array.Test1()
	//array.Test2()
	//array.Test3()
	//array.Test4()
	//array.Test5()
	//array.Test6()
	//array.ExecCode1()
	//array.ExecCode2()
	//array.ExecCode3()
	//array.ExecCode4()
	//array.ExecCode5()
	//array.ExecCode6()
	//array.ExecCode7()
	// 切片
	//slice.STest()
	//slice.MackS()
	//slice.SSlice()
	//slice.SCopy()
	//slice.RSlice()
	//slice.AppAlice()
	//slice.CopySlice()
	//slice.DelSlice()
	//slice.SExec1()
	//slice.RevSlice()
	//slice.FindS()
	//slice.AppSlice()
	//slice.DeduplicationSlice()
	//slice.BjSlice()
	//slice.MuSlice()
	//slice.R2Slice()
	//mapS.DefMap()
	//mapS.RangMap()
	//mapS.DelMap()
	//mapS.SortMap()
	//mapS.SliceMap()
	//mapS.MapSlice()
	//mapS.MapTest()
	//mapS.StuMap()
	//mapS.DelRep()
	//mapS.SrtCount()
	//mapS.MenPhone()
	//mapS.FindWords()
	//mapS.EquMap()
	//mapS.SwapMap()
	//funcDome.FuncDo()
	//funcDome.FuncDom3()
	//funcDome.FuncDom4()
	//funcDome.FuncDom5()
	//funcDome.FuncDom6()
	//funcDome.FuncDom7()
	//funcDome.DeferDome()
	//funcDome.PanicDome()
	//funcDome.RecoverDome()
	//funcDome.DomeFun01()
	//funcDome.DomeFun02()
	//funcDome.DomeFun03()
	//funcDome.DomeFun04()
	//funcDome.DomeFun05()
	//funcDome.AdvFunc01()
	//funcDome.AdvFunc02()
	//funcDome.AdvFunc03()
	//funcDome.AdvFunc04()
	funcDome.AdvFunc05()

}
